-- BotAgent - Add new columns
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS backstory TEXT;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS llm VARCHAR;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS function_calling_llm VARCHAR;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS max_iter INTEGER DEFAULT 20;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS max_rpm INTEGER;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS max_execution_time INTEGER;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS verbose BOOLEAN DEFAULT FALSE;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS allow_delegation BOOLEAN DEFAULT FALSE;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS reasoning BOOLEAN DEFAULT FALSE;
ALTER TABLE bot_agents ADD COLUMN IF NOT EXISTS knowledge_sources JSON;

-- BotTask - Add new columns
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS tools_json JSON;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS context_task_ids JSON;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS async_execution BOOLEAN DEFAULT FALSE;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS output_json_schema JSON;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS output_pydantic_schema JSON;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS callback_config JSON;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS guardrail_config JSON;
ALTER TABLE bot_tasks ADD COLUMN IF NOT EXISTS guardrail_max_retries INTEGER DEFAULT 3;

-- BotCrew - Add new columns
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS verbose BOOLEAN DEFAULT FALSE;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS max_rpm INTEGER;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS manager_llm VARCHAR;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS function_calling_llm VARCHAR;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS manager_agent_id INTEGER REFERENCES bot_agents(id);
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS config_json JSON;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS memory_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS knowledge_sources JSON;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS step_callback_config JSON;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS task_callback_config JSON;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS output_log_file VARCHAR;
ALTER TABLE bot_crews ADD COLUMN IF NOT EXISTS share_crew BOOLEAN DEFAULT FALSE;
